name: ClicSante 2nd Dose Check

on:
  schedule:
    - cron: '*/20 * * * *'

  workflow_dispatch:

jobs:
  # cron:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Ping appointment
        id: step1
        run: |
          response=$(curl --url https://api3.clicsante.ca/v3/appointments/jobs \
            --request POST \
            --header 'Authorization: Basic ${{ secrets.BASIC_TOKEN }}' \
            --data-raw '{"nam":"${{ secrets.APT_ID }}","phone":"${{ secrets.APT_PHONE }}"}' -s)
          response="${response//'%'/'%25'}"
          response="${response//$'\n'/'%0A'}"
          response="${response//$'\r'/'%0D'}"
          echo $response
          echo "::set-output name=body::$response"
          
      - name: Set status
        id: step2
        run: |
          echo "::set-output name=status::${{ fromJson(steps.step1.outputs.body).status }}"
          
      - name: Check status
        id: step3
        if: ${{ steps.step2.outputs.status >= 400 }}
        run: |
          echo "Search for appointment did not yield any result"
          exit 1
